[package]
name = "kyber-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.17.0"
fuzzy-matcher = "0.3.7"
ignore = "0.4.18"
log = "0.4.16"
maplit = "1.0.2"
simple_logger = "2.1.0"
